name: NPM Release

on: 
  workflow_dispatch: {}

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx lerna publish --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Authenticate with Registry
      #   run: |
      #     echo "@dfinity:registry=http://registry.npmjs.org/" > .npmrc
      #     echo "registry=http://registry.npmjs.org/" >> .npmrc
      #     echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      #     npm whoami
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Publish package
      #   run: lerna publish --yes --message 'chore: release new versions'
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_PAT }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
